// Code generated by protoc-gen-go. DO NOT EDIT.
// source: address.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateAddressRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	ParentId             int32    `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAddressRequest) Reset()         { *m = CreateAddressRequest{} }
func (m *CreateAddressRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAddressRequest) ProtoMessage()    {}
func (*CreateAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_982c640dad8fe78e, []int{0}
}

func (m *CreateAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAddressRequest.Unmarshal(m, b)
}
func (m *CreateAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAddressRequest.Marshal(b, m, deterministic)
}
func (m *CreateAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAddressRequest.Merge(m, src)
}
func (m *CreateAddressRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAddressRequest.Size(m)
}
func (m *CreateAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAddressRequest proto.InternalMessageInfo

func (m *CreateAddressRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateAddressRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CreateAddressRequest) GetParentId() int32 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

type Address struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	ParentId             int32    `protobuf:"varint,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_982c640dad8fe78e, []int{1}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Address) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Address) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Address) GetParentId() int32 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

type CreateAddressResponse struct {
	Result               *Address `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAddressResponse) Reset()         { *m = CreateAddressResponse{} }
func (m *CreateAddressResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAddressResponse) ProtoMessage()    {}
func (*CreateAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_982c640dad8fe78e, []int{2}
}

func (m *CreateAddressResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAddressResponse.Unmarshal(m, b)
}
func (m *CreateAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAddressResponse.Marshal(b, m, deterministic)
}
func (m *CreateAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAddressResponse.Merge(m, src)
}
func (m *CreateAddressResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAddressResponse.Size(m)
}
func (m *CreateAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAddressResponse proto.InternalMessageInfo

func (m *CreateAddressResponse) GetResult() *Address {
	if m != nil {
		return m.Result
	}
	return nil
}

type ListAddressesByParentIdAndTypeRequest struct {
	ParentId             int32    `protobuf:"varint,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAddressesByParentIdAndTypeRequest) Reset()         { *m = ListAddressesByParentIdAndTypeRequest{} }
func (m *ListAddressesByParentIdAndTypeRequest) String() string { return proto.CompactTextString(m) }
func (*ListAddressesByParentIdAndTypeRequest) ProtoMessage()    {}
func (*ListAddressesByParentIdAndTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_982c640dad8fe78e, []int{3}
}

func (m *ListAddressesByParentIdAndTypeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAddressesByParentIdAndTypeRequest.Unmarshal(m, b)
}
func (m *ListAddressesByParentIdAndTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAddressesByParentIdAndTypeRequest.Marshal(b, m, deterministic)
}
func (m *ListAddressesByParentIdAndTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAddressesByParentIdAndTypeRequest.Merge(m, src)
}
func (m *ListAddressesByParentIdAndTypeRequest) XXX_Size() int {
	return xxx_messageInfo_ListAddressesByParentIdAndTypeRequest.Size(m)
}
func (m *ListAddressesByParentIdAndTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAddressesByParentIdAndTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAddressesByParentIdAndTypeRequest proto.InternalMessageInfo

func (m *ListAddressesByParentIdAndTypeRequest) GetParentId() int32 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *ListAddressesByParentIdAndTypeRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type ListAddressesByParentIdAndTypeResponse struct {
	Result               []*Address `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListAddressesByParentIdAndTypeResponse) Reset() {
	*m = ListAddressesByParentIdAndTypeResponse{}
}
func (m *ListAddressesByParentIdAndTypeResponse) String() string { return proto.CompactTextString(m) }
func (*ListAddressesByParentIdAndTypeResponse) ProtoMessage()    {}
func (*ListAddressesByParentIdAndTypeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_982c640dad8fe78e, []int{4}
}

func (m *ListAddressesByParentIdAndTypeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAddressesByParentIdAndTypeResponse.Unmarshal(m, b)
}
func (m *ListAddressesByParentIdAndTypeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAddressesByParentIdAndTypeResponse.Marshal(b, m, deterministic)
}
func (m *ListAddressesByParentIdAndTypeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAddressesByParentIdAndTypeResponse.Merge(m, src)
}
func (m *ListAddressesByParentIdAndTypeResponse) XXX_Size() int {
	return xxx_messageInfo_ListAddressesByParentIdAndTypeResponse.Size(m)
}
func (m *ListAddressesByParentIdAndTypeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAddressesByParentIdAndTypeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListAddressesByParentIdAndTypeResponse proto.InternalMessageInfo

func (m *ListAddressesByParentIdAndTypeResponse) GetResult() []*Address {
	if m != nil {
		return m.Result
	}
	return nil
}

type GetAddressByIdRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAddressByIdRequest) Reset()         { *m = GetAddressByIdRequest{} }
func (m *GetAddressByIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetAddressByIdRequest) ProtoMessage()    {}
func (*GetAddressByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_982c640dad8fe78e, []int{5}
}

func (m *GetAddressByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAddressByIdRequest.Unmarshal(m, b)
}
func (m *GetAddressByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAddressByIdRequest.Marshal(b, m, deterministic)
}
func (m *GetAddressByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAddressByIdRequest.Merge(m, src)
}
func (m *GetAddressByIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetAddressByIdRequest.Size(m)
}
func (m *GetAddressByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAddressByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAddressByIdRequest proto.InternalMessageInfo

func (m *GetAddressByIdRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetAddressResponse struct {
	Result               *Address `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAddressResponse) Reset()         { *m = GetAddressResponse{} }
func (m *GetAddressResponse) String() string { return proto.CompactTextString(m) }
func (*GetAddressResponse) ProtoMessage()    {}
func (*GetAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_982c640dad8fe78e, []int{6}
}

func (m *GetAddressResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAddressResponse.Unmarshal(m, b)
}
func (m *GetAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAddressResponse.Marshal(b, m, deterministic)
}
func (m *GetAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAddressResponse.Merge(m, src)
}
func (m *GetAddressResponse) XXX_Size() int {
	return xxx_messageInfo_GetAddressResponse.Size(m)
}
func (m *GetAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAddressResponse proto.InternalMessageInfo

func (m *GetAddressResponse) GetResult() *Address {
	if m != nil {
		return m.Result
	}
	return nil
}

type DeleteAddressRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAddressRequest) Reset()         { *m = DeleteAddressRequest{} }
func (m *DeleteAddressRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAddressRequest) ProtoMessage()    {}
func (*DeleteAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_982c640dad8fe78e, []int{7}
}

func (m *DeleteAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAddressRequest.Unmarshal(m, b)
}
func (m *DeleteAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAddressRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAddressRequest.Merge(m, src)
}
func (m *DeleteAddressRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAddressRequest.Size(m)
}
func (m *DeleteAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAddressRequest proto.InternalMessageInfo

func (m *DeleteAddressRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteAddressResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAddressResponse) Reset()         { *m = DeleteAddressResponse{} }
func (m *DeleteAddressResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAddressResponse) ProtoMessage()    {}
func (*DeleteAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_982c640dad8fe78e, []int{8}
}

func (m *DeleteAddressResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAddressResponse.Unmarshal(m, b)
}
func (m *DeleteAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAddressResponse.Marshal(b, m, deterministic)
}
func (m *DeleteAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAddressResponse.Merge(m, src)
}
func (m *DeleteAddressResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAddressResponse.Size(m)
}
func (m *DeleteAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAddressResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateAddressRequest)(nil), "api.CreateAddressRequest")
	proto.RegisterType((*Address)(nil), "api.Address")
	proto.RegisterType((*CreateAddressResponse)(nil), "api.CreateAddressResponse")
	proto.RegisterType((*ListAddressesByParentIdAndTypeRequest)(nil), "api.ListAddressesByParentIdAndTypeRequest")
	proto.RegisterType((*ListAddressesByParentIdAndTypeResponse)(nil), "api.ListAddressesByParentIdAndTypeResponse")
	proto.RegisterType((*GetAddressByIdRequest)(nil), "api.GetAddressByIdRequest")
	proto.RegisterType((*GetAddressResponse)(nil), "api.GetAddressResponse")
	proto.RegisterType((*DeleteAddressRequest)(nil), "api.DeleteAddressRequest")
	proto.RegisterType((*DeleteAddressResponse)(nil), "api.DeleteAddressResponse")
}

func init() { proto.RegisterFile("address.proto", fileDescriptor_982c640dad8fe78e) }

var fileDescriptor_982c640dad8fe78e = []byte{
	// 359 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xd7, 0x76, 0x9b, 0xee, 0xe9, 0x76, 0x08, 0x1b, 0x9b, 0xd5, 0xc3, 0x08, 0x3a, 0x87,
	0xc2, 0x0e, 0xf3, 0x26, 0x78, 0xd8, 0x14, 0xb6, 0x81, 0x88, 0x54, 0x0f, 0x82, 0xa0, 0x54, 0xf3,
	0x0e, 0x81, 0xd9, 0xc6, 0x26, 0x13, 0xfa, 0x8d, 0xfd, 0x18, 0xb2, 0x36, 0x9d, 0xb6, 0x66, 0x38,
	0x6f, 0xe1, 0xbd, 0xd7, 0xdf, 0xfb, 0xf3, 0x4b, 0x0a, 0x75, 0x9f, 0xb1, 0x08, 0xa5, 0x1c, 0x88,
	0x28, 0x54, 0x21, 0x71, 0x7c, 0xc1, 0xe9, 0x23, 0x34, 0x2f, 0x23, 0xf4, 0x15, 0x8e, 0xd2, 0x9e,
	0x87, 0xef, 0x0b, 0x94, 0x8a, 0x10, 0x28, 0x07, 0xfe, 0x1b, 0x76, 0xac, 0xae, 0xd5, 0xaf, 0x79,
	0xc9, 0x79, 0x59, 0x53, 0xb1, 0xc0, 0x8e, 0x9d, 0xd6, 0x96, 0x67, 0xb2, 0x0f, 0x35, 0xe1, 0x47,
	0x18, 0xa8, 0x67, 0xce, 0x3a, 0x4e, 0xd7, 0xea, 0x57, 0xbc, 0xed, 0xb4, 0x30, 0x63, 0xf4, 0x09,
	0xb6, 0x34, 0x96, 0x34, 0xc0, 0xe6, 0x2c, 0xa1, 0x55, 0x3c, 0x9b, 0xb3, 0x15, 0xdf, 0x36, 0xf0,
	0x9d, 0x75, 0xfc, 0x72, 0x81, 0x7f, 0x01, 0xad, 0x42, 0x78, 0x29, 0xc2, 0x40, 0x22, 0x39, 0x84,
	0x6a, 0x84, 0x72, 0x31, 0x57, 0xc9, 0xc6, 0x9d, 0xe1, 0xee, 0xc0, 0x17, 0x7c, 0x90, 0x4d, 0xe9,
	0x1e, 0x7d, 0x80, 0xa3, 0x6b, 0x2e, 0x95, 0x2e, 0xa3, 0x1c, 0xc7, 0xb7, 0x9a, 0x3c, 0x0a, 0xd8,
	0x7d, 0x2c, 0x30, 0x93, 0x91, 0x0b, 0x61, 0xe5, 0x43, 0x98, 0xac, 0xd0, 0x1b, 0xe8, 0xfd, 0x45,
	0x36, 0x24, 0x75, 0xd6, 0x26, 0x3d, 0x86, 0xd6, 0x04, 0x33, 0xdc, 0x38, 0x9e, 0xb1, 0x2c, 0x59,
	0x41, 0x2b, 0x3d, 0x07, 0xf2, 0x3d, 0xf8, 0x4f, 0x1d, 0x3d, 0x68, 0x5e, 0xe1, 0x1c, 0x7f, 0x3d,
	0x85, 0xe2, 0x8e, 0x36, 0xb4, 0x0a, 0x73, 0xe9, 0x9a, 0xe1, 0xa7, 0x0d, 0x0d, 0x5d, 0xbb, 0xc3,
	0xe8, 0x83, 0xbf, 0x22, 0x99, 0x42, 0x3d, 0x77, 0x43, 0x64, 0x2f, 0x59, 0x6d, 0x7a, 0x72, 0xae,
	0x6b, 0x6a, 0xa5, 0x68, 0x5a, 0x22, 0x31, 0x1c, 0x18, 0x95, 0x6a, 0xa1, 0xe4, 0x24, 0xf9, 0x7a,
	0xa3, 0xfb, 0x74, 0x4f, 0x37, 0x9a, 0x5d, 0xad, 0x9e, 0x40, 0x23, 0x6f, 0x9f, 0xa4, 0x51, 0x8d,
	0x57, 0xe2, 0xb6, 0x0b, 0xbd, 0x1f, 0xa0, 0x29, 0xd4, 0x73, 0xe6, 0xb4, 0x0d, 0x93, 0x75, 0x6d,
	0xc3, 0x28, 0x9a, 0x96, 0x5e, 0xaa, 0xc9, 0x2f, 0x7c, 0xf6, 0x15, 0x00, 0x00, 0xff, 0xff, 0x25,
	0x5b, 0xd6, 0x8f, 0xd3, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AddressServiceClient is the client API for AddressService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AddressServiceClient interface {
	CreateAddress(ctx context.Context, in *CreateAddressRequest, opts ...grpc.CallOption) (*CreateAddressResponse, error)
	ListAddressesByParentAndType(ctx context.Context, in *ListAddressesByParentIdAndTypeRequest, opts ...grpc.CallOption) (*ListAddressesByParentIdAndTypeResponse, error)
	GetAddressById(ctx context.Context, in *GetAddressByIdRequest, opts ...grpc.CallOption) (*GetAddressResponse, error)
	DeleteAddress(ctx context.Context, in *DeleteAddressRequest, opts ...grpc.CallOption) (*DeleteAddressResponse, error)
}

type addressServiceClient struct {
	cc *grpc.ClientConn
}

func NewAddressServiceClient(cc *grpc.ClientConn) AddressServiceClient {
	return &addressServiceClient{cc}
}

func (c *addressServiceClient) CreateAddress(ctx context.Context, in *CreateAddressRequest, opts ...grpc.CallOption) (*CreateAddressResponse, error) {
	out := new(CreateAddressResponse)
	err := c.cc.Invoke(ctx, "/api.AddressService/CreateAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressServiceClient) ListAddressesByParentAndType(ctx context.Context, in *ListAddressesByParentIdAndTypeRequest, opts ...grpc.CallOption) (*ListAddressesByParentIdAndTypeResponse, error) {
	out := new(ListAddressesByParentIdAndTypeResponse)
	err := c.cc.Invoke(ctx, "/api.AddressService/ListAddressesByParentAndType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressServiceClient) GetAddressById(ctx context.Context, in *GetAddressByIdRequest, opts ...grpc.CallOption) (*GetAddressResponse, error) {
	out := new(GetAddressResponse)
	err := c.cc.Invoke(ctx, "/api.AddressService/GetAddressById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressServiceClient) DeleteAddress(ctx context.Context, in *DeleteAddressRequest, opts ...grpc.CallOption) (*DeleteAddressResponse, error) {
	out := new(DeleteAddressResponse)
	err := c.cc.Invoke(ctx, "/api.AddressService/DeleteAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddressServiceServer is the server API for AddressService service.
type AddressServiceServer interface {
	CreateAddress(context.Context, *CreateAddressRequest) (*CreateAddressResponse, error)
	ListAddressesByParentAndType(context.Context, *ListAddressesByParentIdAndTypeRequest) (*ListAddressesByParentIdAndTypeResponse, error)
	GetAddressById(context.Context, *GetAddressByIdRequest) (*GetAddressResponse, error)
	DeleteAddress(context.Context, *DeleteAddressRequest) (*DeleteAddressResponse, error)
}

// UnimplementedAddressServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAddressServiceServer struct {
}

func (*UnimplementedAddressServiceServer) CreateAddress(ctx context.Context, req *CreateAddressRequest) (*CreateAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAddress not implemented")
}
func (*UnimplementedAddressServiceServer) ListAddressesByParentAndType(ctx context.Context, req *ListAddressesByParentIdAndTypeRequest) (*ListAddressesByParentIdAndTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAddressesByParentAndType not implemented")
}
func (*UnimplementedAddressServiceServer) GetAddressById(ctx context.Context, req *GetAddressByIdRequest) (*GetAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAddressById not implemented")
}
func (*UnimplementedAddressServiceServer) DeleteAddress(ctx context.Context, req *DeleteAddressRequest) (*DeleteAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAddress not implemented")
}

func RegisterAddressServiceServer(s *grpc.Server, srv AddressServiceServer) {
	s.RegisterService(&_AddressService_serviceDesc, srv)
}

func _AddressService_CreateAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressServiceServer).CreateAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AddressService/CreateAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressServiceServer).CreateAddress(ctx, req.(*CreateAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressService_ListAddressesByParentAndType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAddressesByParentIdAndTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressServiceServer).ListAddressesByParentAndType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AddressService/ListAddressesByParentAndType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressServiceServer).ListAddressesByParentAndType(ctx, req.(*ListAddressesByParentIdAndTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressService_GetAddressById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAddressByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressServiceServer).GetAddressById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AddressService/GetAddressById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressServiceServer).GetAddressById(ctx, req.(*GetAddressByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressService_DeleteAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressServiceServer).DeleteAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AddressService/DeleteAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressServiceServer).DeleteAddress(ctx, req.(*DeleteAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AddressService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.AddressService",
	HandlerType: (*AddressServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAddress",
			Handler:    _AddressService_CreateAddress_Handler,
		},
		{
			MethodName: "ListAddressesByParentAndType",
			Handler:    _AddressService_ListAddressesByParentAndType_Handler,
		},
		{
			MethodName: "GetAddressById",
			Handler:    _AddressService_GetAddressById_Handler,
		},
		{
			MethodName: "DeleteAddress",
			Handler:    _AddressService_DeleteAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "address.proto",
}
