// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Address struct {
	ID       int64
	Type     string
	Name     string
	ParentID pgtype.Int4
}
